name: Release Action

on:
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  check_version:
    name: Check version
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      packages: write
    outputs:
      is_version_increased: ${{ steps.compare_versions.outputs.is_version_increased }}
      version: ${{ steps.package-version.outputs.current-version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: 'main'

      - name: get-npm-version
        id: package-version-prev
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Checkout
        uses: actions/checkout@v4

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Compare versions
        id: compare_versions
        run: |
          if [ "${{ steps.package-version-prev.outputs.current-version }}" == "${{ steps.package-version.outputs.current-version }}" ]; then
            echo "::error::Version has not been increased, action cancelled..." && exit 1
          fi

  check_if_release_exists:
    name: Check if release exists
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: check_version
    if: needs.check_version.outputs.is_version_increased == 'true'
    permissions:
      contents: read
      packages: write
    outputs:
      release_exists: ${{ steps.check_release.outputs.release_exists }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4


      - name: Check if release exists
        id: check_release
        env:
          GH_TOKEN: ${{ github.token }}
          tag: ${{ needs.check_version.outputs.version }}
        run: |
          echo "$(gh release view "$tag" 2>&1)"
          if [ "$(gh release view "$tag" 2>&1)" == "release not found" ]; then
            echo "Release does not exist"
            echo "release_exists=false" >> "$GITHUB_OUTPUT"
          else
            echo "Release exists"
            echo "release_exists=true" >> "$GITHUB_OUTPUT"
            exit 1
          fi

